version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - ./volumnes/data/db:/data/db
    networks:
      - network1

networks:
   network1: