# file name to write a report
filename: "test-write-file.log"

# mongodb credential
mongodb:
  host: localhost
  port: 27017
  user: test
  password: test
  database: evhousekeeper
  collection: evhousekeeper